apiVersion: vi
kind: ClusterServices

metadata:
  cluster: callmatic-3
  region: ap-south-1
  version: "1.33"
  git:
    key_path: testpod
    username: abhinav054
    email: abhinav054@gmail.com

namespaces:
  - name: test
    services:
      - name: nginx
        type: service
        container: docker
        commit: "latest"
        repo: "git@github.com:abhinav054/testpod.git"
        branch: "main"
        cmd: ""
        buildCmd: ""
        envs: "test.env,newtest.env"
        mem_requests: "128Mi"
        mem_limits: "128Mi"
        cpu_requests: 0.5
        cpu_limits: 0.5
        pod_requests: 1
        pod_limits: 1
        public_lb: true
        sourceRanges: ""
        exposePort: 80
        servicePort: 80
      - name: testjob
        type: job
        container: docker
        commit: "latest"
        repo: "git@github.com:abhinav054/busybox-echo.git"
        branch: "main"
        cmd: ""
        buildCmd: ""
        envs: ""
        mem_requests: "128Mi"
        mem_limits: "128Mi"
        cpu_requests: 0.5
        cpu_limits: 0.5
        

        